import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      nav: { home: "Home", listings: "Listings", map: "Map", saved: "Saved", dashboard: "Dashboard", admin: "Admin", profile: "Profile", myListings: "My Listings", adminPanel: "Admin Panel", signIn: "Sign In", getStarted: "Get Started", signOut: "Sign Out" },
      home: { searchPlaceholder: "Search by location, street name...", heroTitle: "Find Your Perfect", heroHighlight: "Boarding Room", heroSubtitle: "Nearby Trincomalee Campus", heroDesc: "Discover verified, affordable boarding rooms recommended by the campus. Browse rooms on the map, read student reviews, and find your ideal home away from home.", browseCTA: "Browse Rooms", mapCTA: "View on Map", topRated: "Top Rated Rooms", recommended: "Recommended for You", recentlyAdded: "Recently Added", viewAll: "View All", statsStudents: "Active Students", statsListings: "Verified Listings", statsReviews: "Student Reviews", statsOwners: "Verified Owners" },
      listing: { price: "Price", perMonth: "/month", deposit: "Deposit", distance: "Distance", fromCampus: "from campus", facilities: "Facilities", rules: "Rules", reviews: "Reviews", writeReview: "Write a Review", contactOwner: "Contact Owner", verified: "Verified", available: "Available", occupied: "Occupied", pending: "Pending", single: "Single Room", shared: "Shared Room", "full house": "Full House", addToFav: "Add to Favorites", removeFromFav: "Remove from Favorites", description: "Description", viewDetails: "View Details", ownerInfo: "Owner Info", tenantPref: "Tenant Preferences", boysOnly: "Boys only", girlsOnly: "Girls only", anyone: "Anyone", noResults: "No rooms found", tryDifferent: "Try adjusting your filters" },
      filter: { priceRange: "Price Range", roomType: "Room Type", allTypes: "All Types", maxDistance: "Max Distance", searchPlaceholder: "Search rooms...", applyFilters: "Apply Filters", clearAll: "Clear All", sortBy: "Sort By", newest: "Newest", priceLow: "Price: Low to High", priceHigh: "Price: High to Low", rating: "Highest Rated" },
      auth: { login: "Sign In", register: "Create Account", email: "Email Address", password: "Password", confirmPassword: "Confirm Password", name: "Full Name", phone: "Phone Number", loginTitle: "Welcome Back", loginSubtitle: "Sign in to find your perfect boarding room", registerTitle: "Join UniBoard", registerSubtitle: "Create an account to get started", asStudent: "As Student", asOwner: "As Room Owner", orContinueWith: "or continue with", googleSignIn: "Continue with Google", noAccount: "Don't have an account?", hasAccount: "Already have an account?", forgotPassword: "Forgot password?" },
      owner: { dashboard: "Owner Dashboard", myRooms: "My Rooms", addRoom: "Add New Room", editRoom: "Edit Room", totalViews: "Total Views", totalFavorites: "Total Favorites", activeListings: "Active Listings", roomTitle: "Room Title", roomDesc: "Description", roomPrice: "Monthly Rent (LKR)", roomDeposit: "Security Deposit (LKR)", roomAddress: "Address", roomFacilities: "Facilities", roomType: "Room Type", uploadPhotos: "Upload Photos", dropPin: "Drop Pin on Map", tenantPref: "Tenant Preferences", gender: "Gender Preference", saveListing: "Save Listing", markAvailable: "Mark Available", markOccupied: "Mark Occupied", deleteListing: "Delete Listing", analytics: "Analytics", viewsThisWeek: "Views This Week", favsThisWeek: "Favorites This Week", basicInfo: "Basic Information", contactInfo: "Contact Information", locationMap: "Location & Map" },
      admin: { dashboard: "Admin Dashboard", overview: "Overview", users: "Users", verifications: "Verifications", listings: "Listings", totalUsers: "Total Users", students: "Students", owners: "Owners", activeListings: "Active Listings", pendingListings: "Pending Listings", pendingVerifications: "Pending Verifications", approve: "Approve", reject: "Reject", ban: "Ban", unban: "Unban", viewDoc: "View Document", resolve: "Resolve", dismiss: "Dismiss" },
      facilities: { kitchen: "Kitchen", bathroom: "Attached Bathroom", parking: "Parking", laundry: "Laundry", security: "Security", furnished: "Furnished", water: "24/7 Water", electricity: "Electricity", tv: "TV" },
      footer: { about: "About UniBoard", aboutDesc: "A platform helping Eastern University Trincomalee students find safe, affordable boarding rooms near campus.", quickLinks: "Quick Links", support: "Support", legal: "Legal", contactUs: "Contact Us", helpCenter: "Help Center", terms: "Terms of Service", privacy: "Privacy Policy", rights: "All rights reserved." }
    }
  },
  si: {
    translation: {
      nav: { home: "මුල් පිටුව", listings: "කාමර", map: "සිතියම", saved: "සුරකින ලද", dashboard: "පුවරුව", admin: "පරිපාලක", profile: "පැතිකඩ", myListings: "මගේ කාමර", adminPanel: "පරිපාලක පැනලය", signIn: "පුරනය", getStarted: "ආරම්භ කරන්න", signOut: "පිටවීම" },
      home: { searchPlaceholder: "ස්ථානය, වීදිය මගින් සොයන්න...", heroTitle: "ඔබේ සුදුසු", heroHighlight: "නේවාසිකාගාරය", heroSubtitle: "ත්‍රිකුණාමලය මණ්ඩපය අසල", heroDesc: "විශ්වවිද්‍යාලය විසින් නිර්දේශිත, සත්‍යාපිත සහ දැරිය හැකි නේවාසිකාගාර සොයා ගන්න.", browseCTA: "කාමර බලන්න", mapCTA: "සිතියමේ බලන්න", topRated: "ඉහළම ශ්‍රේණිගත කාමර", recommended: "ඔබ සඳහා නිර්දේශිත", recentlyAdded: "මෑතකදී එකතු කළ", viewAll: "සියල්ල බලන්න", statsStudents: "සක්‍රීය සිසුන්", statsListings: "සත්‍යාපිත කාමර", statsReviews: "සිසු සමාලෝචන", statsOwners: "සත්‍යාපිත හිමිකරුවන්" },
      listing: { price: "මිල", perMonth: "/මසකට", deposit: "තැන්පතු", distance: "දුර", fromCampus: "සරසවියෙන්", facilities: "පහසුකම්", rules: "නීති", reviews: "සමාලෝචන", writeReview: "සමාලෝචනයක් ලියන්න", contactOwner: "හිමිකරු සම්බන්ධ කරගන්න", verified: "සත්‍යාපිත", available: "පවතී", occupied: "පිරී ඇත", pending: "අපේක්ෂාවෙන්", single: "තනි කාමරය", shared: "බෙදාගත් කාමරය", "full house": "සම්පූර්ණ නිවස", addToFav: "ප්‍රියතමයට", removeFromFav: "ප්‍රියතමයෙන් ඉවත් කරන්න", viewDetails: "විස්තර බලන්න", ownerInfo: "හිමිකරු තොරතුරු", tenantPref: "කුලී නිවැසියන් මනාපය", boysOnly: "පිරිමි ළමුන් සඳහා පමණි", girlsOnly: "ගැහැණු ළමුන් සඳහා පමණි", anyone: "ඕනෑම කෙනෙකුට", noResults: "කාමර හමු නොවීය", tryDifferent: "ඔබේ පෙරහන් වෙනස් කරන්න" },
      filter: { priceRange: "මිල පරාසය", roomType: "කාමර වර්ගය", allTypes: "සියලු වර්ග", maxDistance: "උපරිම දුර", searchPlaceholder: "කාමර සොයන්න...", applyFilters: "පෙරහන් යොදන්න", clearAll: "සියල්ල මකන්න", sortBy: "අනුපිළිවෙලට", newest: "නවතම", priceLow: "අඩුම මිල", priceHigh: "වැඩිම මිල", rating: "ඉහළම ශ්‍රේණිගත" },
      auth: { login: "පුරනය වන්න", register: "ගිණුමක් සාදන්න", email: "ඊමේල් ලිපිනය", password: "මුරපදය", confirmPassword: "මුරපදය තහවුරු කරන්න", name: "සම්පූර්ණ නම", phone: "දුරකථන අංකය", loginTitle: "නැවත සාදරයෙන් පිළිගනිමු", loginSubtitle: "ඔබේ නේවාසිකාගාරය සොයා ගැනීමට පුරනය වන්න", registerTitle: "UniBoard එකට සම්බන්ධ වන්න", registerSubtitle: "ආරම්භ කිරීමට ගිණුමක් සාදන්න", asStudent: "සිසුවෙක් ලෙස", asOwner: "කාමර හිමිකරුවෙක් ලෙස", orContinueWith: "හෝ දිගටම", googleSignIn: "Google සමඟ", noAccount: "ගිණුමක් නැද්ද?", hasAccount: "දැනටමත් ගිණුමක් තිබේද?", forgotPassword: "මුරපදය අමතකද?" },
      owner: { dashboard: "හිමිකරු පුවරුව", myRooms: "මගේ කාමර", addRoom: "නව කාමරයක් එකතු කරන්න", editRoom: "කාමරය සංස්කරණය", totalViews: "මුළු බැලීම්", totalFavorites: "මුළු ප්‍රියතම", activeListings: "සක්‍රීය කාමර", roomTitle: "කාමර මාතෘකාව", roomDesc: "විස්තරය", roomPrice: "මාසික කුලිය (රු.)", roomDeposit: "ආරක්ෂක තැන්පතුව (රු.)", roomAddress: "ලිපිනය", roomFacilities: "පහසුකම්", roomType: "කාමර වර්ගය", uploadPhotos: "ඡායාරූප උඩුගත", dropPin: "සිතියමේ පින් දමන්න", tenantPref: "කුලී නිවැසියන් මනාප", gender: "ලිංග මනාපය", saveListing: "සුරකින්න", markAvailable: "ලබාගත හැකි ලෙස", markOccupied: "පිරී ඇති ලෙස", deleteListing: "මකන්න", analytics: "විශ්ලේෂණ", viewsThisWeek: "මේ සතියේ බැලීම්", favsThisWeek: "මේ සතියේ ප්‍රියතම", basicInfo: "මූලික තොරතුරු", contactInfo: "සම්බන්ධතා තොරතුරු", locationMap: "ස්ථානය සහ සිතියම" },
      admin: { dashboard: "පරිපාලක පුවරුව", overview: "දළ විස්තරය", users: "පරිශීලකයින්", verifications: "සත්‍යාපන", listings: "කාමර", totalUsers: "මුළු පරිශීලකයින්", students: "සිසුන්", owners: "හිමිකරුවන්", activeListings: "සක්‍රීය කාමර", pendingListings: "අපේක්ෂාවෙන් කාමර", pendingVerifications: "අපේක්ෂාවෙන් සත්‍යාපන", approve: "අනුමත කරන්න", reject: "ප්‍රතික්ෂේප කරන්න", ban: "තහනම් කරන්න", unban: "තහනම ඉවත් කරන්න", viewDoc: "ලේඛනය බලන්න", resolve: "විසඳන්න", dismiss: "ඉවත් කරන්න" },
      facilities: { kitchen: "මුළුතැන්ගෙය", bathroom: "ඇමුණු නාන කාමරය", parking: "වාහන නැවතුම", laundry: "රෙදි සෝදන", security: "ආරක්ෂාව", furnished: "ගෘහ භාණ්ඩ සහිත", water: "24/7 ජලය", electricity: "විදුලිය", tv: "TV" },
      footer: { about: "UniBoard ගැන", aboutDesc: "නැගෙනහිර විශ්වවිද්‍යාලය ත්‍රිකුණාමලය සිසුන්ට ආරක්ෂිත නේවාසිකාගාර සොයා ගැනීමට උපකාර කරන වේදිකාවකි.", quickLinks: "ඉක්මන් සබැඳි", support: "සහාය", legal: "නීතිමය", contactUs: "අප අමතන්න", helpCenter: "උදව් මධ්‍යස්ථානය", terms: "සේවා නියම", privacy: "පෞද්ගලිකත්ව ප්‍රතිපත්තිය", rights: "සියලු හිමිකම් ඇවිරිණි." }
    }
  },
  ta: {
    translation: {
      nav: { home: "முகப்பு", listings: "அறைகள்", map: "வரைபடம்", saved: "சேமித்தவை", dashboard: "டாஷ்போர்டு", admin: "நிர்வாகி", profile: "சுயவிவரம்", myListings: "என் அறைகள்", adminPanel: "நிர்வாக பேனல்", signIn: "உள்நுழைக", getStarted: "தொடங்குங்கள்", signOut: "வெளியேறு" },
      home: { searchPlaceholder: "இடம், தெரு பெயரால் தேடு...", heroTitle: "உங்கள் சிறந்த", heroHighlight: "தங்கும் அறை", heroSubtitle: "திருகோணமலை வளாகம் அருகில்", heroDesc: "வளாகத்தால் பரிந்துரைக்கப்பட்ட, சரிபார்க்கப்பட்ட மற்றும் மலிவான தங்கும் அறைகளைக் கண்டறியுங்கள்.", browseCTA: "அறைகளை பாருங்கள்", mapCTA: "வரைபடத்தில் காண", topRated: "சிறந்த மதிப்பீடு", recommended: "உங்களுக்கான பரிந்துரை", recentlyAdded: "சமீபத்தில் சேர்க்கப்பட்டவை", viewAll: "அனைத்தும் காண", statsStudents: "செயலில் மாணவர்கள்", statsListings: "சரிபார்க்கப்பட்ட அறைகள்", statsReviews: "மாணவர் மதிப்புரைகள்", statsOwners: "சரிபார்க்கப்பட்ட உரிமையாளர்கள்" },
      listing: { price: "விலை", perMonth: "/மாதம்", deposit: "வைப்பு", distance: "தூரம்", fromCampus: "வளாகத்திலிருந்து", facilities: "வசதிகள்", rules: "விதிகள்", reviews: "மதிப்புரைகள்", writeReview: "மதிப்புரை எழுது", contactOwner: "உரிமையாளரை தொடர்பு கொள்ள", verified: "சரிபார்க்கப்பட்டது", available: "கிடைக்கிறது", occupied: "நிரம்பியுள்ளது", pending: "நிலுவையில்", single: "தனி அறை", shared: "பகிர்ந்த அறை", "full house": "முழு வீடு", addToFav: "பிடித்தவைக்கு சேர்", removeFromFav: "பிடித்தவையிலிருந்து நீக்கு", description: "விளக்கம்", viewDetails: "விவரங்கள் காண", ownerInfo: "உரிமையாளர் தகவல்", tenantPref: "குத்தகைதாரர் விருப்பம்", boysOnly: "ஆண்கள் மட்டும்", girlsOnly: "பெண்கள் மட்டும்", anyone: "யாவருக்கும்", noResults: "அறைகள் கிடைக்கவில்லை", tryDifferent: "வடிகட்டிகளை மாற்றி முயற்சிக்கவும்" },
      filter: { priceRange: "விலை வரம்பு", roomType: "அறை வகை", allTypes: "அனைத்து வகைகள்", maxDistance: "அதிகபட்ச தூரம்", searchPlaceholder: "அறைகளை தேடு...", applyFilters: "வடிகட்டிகளை பயன்படுத்து", clearAll: "அனைத்தையும் அழி", sortBy: "வரிசைப்படுத்து", newest: "புதியவை", priceLow: "குறைந்த விலை", priceHigh: "அதிக விலை", rating: "சிறந்த மதிப்பீடு" },
      auth: { login: "உள்நுழைக", register: "கணக்கை உருவாக்கு", email: "மின்னஞ்சல் முகவரி", password: "கடவுச்சொல்", confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து", name: "முழு பெயர்", phone: "தொலைபேசி எண்", loginTitle: "மீண்டும் வரவேற்கிறோம்", loginSubtitle: "உங்கள் தங்கும் அறையைக் கண்டறிய உள்நுழையவும்", registerTitle: "UniBoard இல் இணையுங்கள்", registerSubtitle: "தொடங்க கணக்கை உருவாக்கவும்", asStudent: "மாணவராக", asOwner: "அறை உரிமையாளராக", orContinueWith: "அல்லது தொடரவும்", googleSignIn: "Google உடன் தொடரவும்", noAccount: "கணக்கு இல்லையா?", hasAccount: "ஏற்கனவே கணக்கு உள்ளதா?", forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?" },
      owner: { dashboard: "உரிமையாளர் டாஷ்போர்டு", myRooms: "என் அறைகள்", addRoom: "புதிய அறை சேர்", editRoom: "அறையை திருத்து", totalViews: "மொத்த பார்வைகள்", totalFavorites: "மொத்த பிடித்தவை", activeListings: "செயலில் அறைகள்", roomTitle: "அறை தலைப்பு", roomDesc: "விளக்கம்", roomPrice: "மாத வாடகை (ரூ.)", roomDeposit: "பாதுகாப்பு வைப்பு (ரூ.)", roomAddress: "முகவரி", roomFacilities: "வசதிகள்", roomType: "அறை வகை", uploadPhotos: "புகைப்படங்கள் பதிவேற்றம்", dropPin: "வரைபடத்தில் குறிக்கவும்", tenantPref: "குத்தகைதாரர் விருப்பம்", gender: "பாலின விருப்பம்", saveListing: "சேமிக்கவும்", markAvailable: "கிடைக்கும் என குறி", markOccupied: "நிரம்பியது என குறி", deleteListing: "நீக்கு", analytics: "பகுப்பாய்வு", viewsThisWeek: "இந்த வார பார்வைகள்", favsThisWeek: "இந்த வார பிடித்தவை", basicInfo: "அடிப்படை தகவல்", contactInfo: "தொடர்பு தகவல்", locationMap: "இடம் மற்றும் வரைபடம்" },
      admin: { dashboard: "நிர்வாக டாஷ்போர்டு", overview: "கண்ணோட்டம்", users: "பயனர்கள்", verifications: "சரிபார்ப்புகள்", listings: "அறைகள்", totalUsers: "மொத்த பயனர்கள்", students: "மாணவர்கள்", owners: "உரிமையாளர்கள்", activeListings: "செயலில் அறைகள்", pendingListings: "நிலுவை அறைகள்", pendingVerifications: "நிலுவை சரிபார்ப்புகள்", approve: "ஏற்கவும்", reject: "நிராகரிக்கவும்", ban: "தடை செய்", unban: "தடை நீக்கு", viewDoc: "ஆவணம் காண", resolve: "தீர்க்கவும்", dismiss: "நிராகரிக்கவும்" },
      facilities: { kitchen: "சமையலறை", bathroom: "இணைக்கப்பட்ட குளியலறை", parking: "வாகன நிறுத்தம்", laundry: "சலவை", security: "பாதுகாப்பு", furnished: "அலங்கரிக்கப்பட்ட", water: "24/7 தண்ணீர்", electricity: "மின்சாரம்", tv: "TV" },
      footer: { about: "UniBoard பற்றி", aboutDesc: "கிழக்கு பல்கலைக்கழகம் திருகோணமலை மாணவர்களுக்கு பாதுகாப்பான தங்கும் அறைகளைக் கண்டறிய உதவும் தளம்.", quickLinks: "விரைவு இணைப்புகள்", support: "ஆதரவு", legal: "சட்ட", contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்", helpCenter: "உதவி மையம்", terms: "சேவை விதிமுறைகள்", privacy: "தனியுரிமை கொள்கை", rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை." }
    }
  }
};

i18n.use(initReactI18next).init({
  resources, lng: 'en', fallbackLng: 'en',
  interpolation: { escapeValue: false }
});

export default i18n;

/*
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      nav: { home: "Home", listings: "Listings", map: "Map", saved: "Saved", dashboard: "Dashboard", admin: "Admin", profile: "Profile", myListings: "My Listings", adminPanel: "Admin Panel", signIn: "Sign In", getStarted: "Get Started", signOut: "Sign Out" },
      home: { searchPlaceholder: "Search by location, street name...", heroTitle: "Find Your Perfect", heroHighlight: "Boarding Room", heroSubtitle: "Nearby Trincomalee Campus", heroDesc: "Discover verified, affordable boarding rooms recommended by the campus. Browse rooms on the map, read student reviews, and find your ideal home away from home.", browseCTA: "Browse Rooms", mapCTA: "View on Map", topRated: "Top Rated Rooms", recommended: "Recommended for You", recentlyAdded: "Recently Added", viewAll: "View All", statsStudents: "Active Students", statsListings: "Verified Listings", statsReviews: "Student Reviews", statsOwners: "Verified Owners" },
      listing: { price: "Price", perMonth: "/month", deposit: "Deposit", distance: "Distance", fromCampus: "from campus", facilities: "Facilities", rules: "Rules", reviews: "Reviews", writeReview: "Write a Review", contactOwner: "Contact Owner", verified: "Verified", available: "Available", occupied: "Occupied", pending: "Pending", single: "Single Room", shared: "Shared Room", "full house": "Full House", addToFav: "Add to Favorites", removeFromFav: "Remove from Favorites", viewDetails: "View Details", ownerInfo: "Owner Info", tenantPref: "Tenant Preferences", boysOnly: "Boys only", girlsOnly: "Girls only", anyone: "Anyone", noResults: "No rooms found", tryDifferent: "Try adjusting your filters" },
      filter: { priceRange: "Price Range", roomType: "Room Type", allTypes: "All Types", maxDistance: "Max Distance", searchPlaceholder: "Search rooms...", applyFilters: "Apply Filters", clearAll: "Clear All", sortBy: "Sort By", newest: "Newest", priceLow: "Price: Low to High", priceHigh: "Price: High to Low", rating: "Highest Rated" },
      auth: { login: "Sign In", register: "Create Account", email: "Email Address", password: "Password", confirmPassword: "Confirm Password", name: "Full Name", phone: "Phone Number", loginTitle: "Welcome Back", loginSubtitle: "Sign in to find your perfect boarding room", registerTitle: "Join UniBoard", registerSubtitle: "Create an account to get started", asStudent: "As Student", asOwner: "As Room Owner", orContinueWith: "or continue with", googleSignIn: "Continue with Google", noAccount: "Don't have an account?", hasAccount: "Already have an account?", forgotPassword: "Forgot password?" },
      owner: { dashboard: "Owner Dashboard", myRooms: "My Rooms", addRoom: "Add New Room", editRoom: "Edit Room", totalViews: "Total Views", totalFavorites: "Total Favorites", activeListings: "Active Listings", roomTitle: "Room Title", roomDesc: "Description", roomPrice: "Monthly Rent (LKR)", roomDeposit: "Security Deposit (LKR)", roomAddress: "Address", roomFacilities: "Facilities", roomType: "Room Type", uploadPhotos: "Upload Photos", dropPin: "Drop Pin on Map", tenantPref: "Tenant Preferences", gender: "Gender Preference", saveListing: "Save Listing", markAvailable: "Mark Available", markOccupied: "Mark Occupied", deleteListing: "Delete Listing", analytics: "Analytics", viewsThisWeek: "Views This Week", favsThisWeek: "Favorites This Week", basicInfo: "Basic Information", contactInfo: "Contact Information", locationMap: "Location & Map" },
      admin: { dashboard: "Admin Dashboard", overview: "Overview", users: "Users", verifications: "Verifications", listings: "Listings", totalUsers: "Total Users", students: "Students", owners: "Owners", activeListings: "Active Listings", pendingListings: "Pending Listings", pendingVerifications: "Pending Verifications", approve: "Approve", reject: "Reject", ban: "Ban", unban: "Unban", viewDoc: "View Document", resolve: "Resolve", dismiss: "Dismiss" },
      facilities: { kitchen: "Kitchen", bathroom: "Attached Bathroom", parking: "Parking", laundry: "Laundry", security: "Security", furnished: "Furnished", water: "24/7 Water", electricity: "Electricity", tv: "TV" },
      footer: { about: "About UniBoard", aboutDesc: "A platform helping Eastern University Trincomalee students find safe, affordable boarding rooms near campus.", quickLinks: "Quick Links", support: "Support", legal: "Legal", contactUs: "Contact Us", helpCenter: "Help Center", terms: "Terms of Service", privacy: "Privacy Policy", rights: "All rights reserved." }
    }
  },
  si: {
    translation: {
      nav: { home: "මුල් පිටුව", listings: "කාමර", map: "සිතියම", saved: "සුරකින ලද", dashboard: "පුවරුව", admin: "පරිපාලක", profile: "පැතිකඩ", myListings: "මගේ කාමර", adminPanel: "පරිපාලක පැනලය", signIn: "පුරනය", getStarted: "ආරම්භ කරන්න", signOut: "පිටවීම" },
      home: { searchPlaceholder: "ස්ථානය, වීදිය මගින් සොයන්න...", heroTitle: "ඔබේ සුදුසු", heroHighlight: "නේවාසිකාගාරය", heroSubtitle: "ත්‍රිකුණාමලය මණ්ඩපය අසල", heroDesc: "විශ්වවිද්‍යාලය විසින් නිර්දේශිත, සත්‍යාපිත සහ දැරිය හැකි නේවාසිකාගාර සොයා ගන්න.", browseCTA: "කාමර බලන්න", mapCTA: "සිතියමේ බලන්න", topRated: "ඉහළම ශ්‍රේණිගත කාමර", recommended: "ඔබ සඳහා නිර්දේශිත", recentlyAdded: "මෑතකදී එකතු කළ", viewAll: "සියල්ල බලන්න", statsStudents: "සක්‍රීය සිසුන්", statsListings: "සත්‍යාපිත කාමර", statsReviews: "සිසු සමාලෝචන", statsOwners: "සත්‍යාපිත හිමිකරුවන්" },
      listing: { price: "මිල", perMonth: "/මසකට", deposit: "තැන්පතු", distance: "දුර", fromCampus: "සරසවියෙන්", facilities: "පහසුකම්", rules: "නීති", reviews: "සමාලෝචන", writeReview: "සමාලෝචනයක් ලියන්න", contactOwner: "හිමිකරු සම්බන්ධ කරගන්න", verified: "සත්‍යාපිත", available: "පවතී", occupied: "පිරී ඇත", pending: "අනුමැතිය අපේක්ෂාවෙන්", single: "තනි කාමරය", shared: "බෙදාගත් කාමරය", "full house": "සම්පූර්ණ නිවස", addToFav: "ප්‍රියතමයට", removeFromFav: "ප්‍රියතමයෙන් ඉවත් කරන්න", description: "විස්තරය", viewDetails: "විස්තර බලන්න", ownerInfo: "හිමිකරු තොරතුරු", tenantPref: "කුලී නිවැසියන් මනාපය", boysOnly: "පිරිමි ළමුන් සඳහා පමණි", girlsOnly: "ගැහැණු ළමුන් සඳහා පමණි", anyone: "ඕනෑම කෙනෙකුට", noResults: "කාමර හමු නොවීය", tryDifferent: "ඔබේ පෙරහන් වෙනස් කරන්න" },
      filter: { priceRange: "මිල පරාසය", roomType: "කාමර වර්ගය", allTypes: "සියලු වර්ග", maxDistance: "උපරිම දුර", searchPlaceholder: "කාමර සොයන්න...", applyFilters: "පෙරහන් යොදන්න", clearAll: "සියල්ල මකන්න", sortBy: "අනුපිළිවෙලට", newest: "නවතම", priceLow: "අඩුම මිල", priceHigh: "වැඩිම මිල", rating: "ඉහළම ශ්‍රේණිගත" },
      auth: { login: "පුරනය වන්න", register: "ගිණුමක් සාදන්න", email: "ඊමේල් ලිපිනය", password: "මුරපදය", confirmPassword: "මුරපදය තහවුරු කරන්න", name: "සම්පූර්ණ නම", phone: "දුරකථන අංකය", loginTitle: "නැවත සාදරයෙන් පිළිගනිමු", loginSubtitle: "ඔබේ නේවාසිකාගාරය සොයා ගැනීමට පුරනය වන්න", registerTitle: "UniBoard එකට සම්බන්ධ වන්න", registerSubtitle: "ආරම්භ කිරීමට ගිණුමක් සාදන්න", asStudent: "සිසුවෙක් ලෙස", asOwner: "කාමර හිමිකරුවෙක් ලෙස", orContinueWith: "නැතහොත් මේ හරහා ඉදිරියට යන්න", googleSignIn: "Google සමඟ", noAccount: "ගිණුමක් නැද්ද?", hasAccount: "දැනටමත් ගිණුමක් තිබේද?", forgotPassword: "මුරපදය අමතකද?" },
      owner: { dashboard: "හිමිකරු පුවරුව", myRooms: "මගේ කාමර", addRoom: "නව කාමරයක් එකතු කරන්න", editRoom: "කාමරය සංස්කරණය", totalViews: "මුළු බැලීම්", totalFavorites: "මුළු ප්‍රියතම", activeListings: "සක්‍රීය කාමර", roomTitle: "කාමර මාතෘකාව", roomDesc: "විස්තරය", roomPrice: "මාසික කුලිය (රු.)", roomDeposit: "ආරක්ෂක තැන්පතුව (රු.)", roomAddress: "ලිපිනය", roomFacilities: "පහසුකම්", roomType: "කාමර වර්ගය", uploadPhotos: "ඡායාරූප උඩුගත", dropPin: "සිතියමේ ස්ථානය ලකුණු කරන්න", tenantPref: "කුලී නිවැසියන් මනාප", gender: "ලිංග මනාපය", saveListing: "සුරකින්න", markAvailable: "ලබාගත හැකි ලෙස", markOccupied: "පිරී ඇති ලෙස", deleteListing: "මකන්න", analytics: "විශ්ලේෂණ", viewsThisWeek: "මේ සතියේ බැලීම්", favsThisWeek: "මේ සතියේ ප්‍රියතම", basicInfo: "මූලික තොරතුරු", contactInfo: "සම්බන්ධතා තොරතුරු", locationMap: "ස්ථානය සහ සිතියම" },
      admin: { dashboard: "පරිපාලක පුවරුව", overview: "දළ විස්තරය", users: "පරිශීලකයින්", verifications: "සත්‍යාපන", listings: "කාමර", totalUsers: "මුළු පරිශීලකයින්", students: "සිසුන්", owners: "හිමිකරුවන්", activeListings: "සක්‍රීය කාමර", pendingListings: "අපේක්ෂාවෙන් කාමර", pendingVerifications: "අපේක්ෂාවෙන් සත්‍යාපන", approve: "අනුමත කරන්න", reject: "ප්‍රතික්ෂේප කරන්න", ban: "තහනම් කරන්න", unban: "තහනම ඉවත් කරන්න", viewDoc: "ලේඛනය බලන්න", resolve: "විසඳන්න", dismiss: "ඉවත් කරන්න" },
      facilities: { kitchen: "මුළුතැන්ගෙය", bathroom: "යාබද නාන කාමරය", parking: "වාහන නැවතුම", laundry: "රෙදි සෝදන", security: "ආරක්ෂාව", furnished: "ගෘහ භාණ්ඩ සහිත", water: "24/7 ජලය", electricity: "විදුලිය", tv: "TV" },
      footer: { about: "UniBoard ගැන", aboutDesc: "නැගෙනහිර විශ්වවිද්‍යාලය ත්‍රිකුණාමලය සිසුන්ට ආරක්ෂිත නේවාසිකාගාර සොයා ගැනීමට උපකාර කරන වේදිකාවකි.", quickLinks: "ඉක්මන් සබැඳි", support: "සහාය", legal: "නීතිමය", contactUs: "අප අමතන්න", helpCenter: "උදව් මධ්‍යස්ථානය", terms: "සේවා නියම", privacy: "පෞද්ගලිකත්ව ප්‍රතිපත්තිය", rights: "සියලු හිමිකම් ඇවිරිණි." }
    }
  },
  ta: {
    translation: {
      nav: { home: "முகப்பு", listings: "அறைகள்", map: "வரைபடம்", saved: "சேமித்தவை", dashboard: "டாஷ்போர்டு", admin: "நிர்வாகி", profile: "சுயவிவரம்", myListings: "என் அறைகள்", adminPanel: "நிர்வாக பேனல்", signIn: "உள்நுழைக", getStarted: "தொடங்குங்கள்", signOut: "வெளியேறு" },
      home: { searchPlaceholder: "இடம், தெரு பெயரால் தேடு...", heroTitle: "உங்கள் சிறந்த", heroHighlight: "தங்கும் அறை", heroSubtitle: "திருகோணமலை வளாகம் அருகில்", heroDesc: "வளாகத்தால் பரிந்துரைக்கப்பட்ட, சரிபார்க்கப்பட்ட மற்றும் கட்டுப்படியான தங்கும் அறைகளைக் கண்டறியுங்கள்.", browseCTA: "அறைகளை பாருங்கள்", mapCTA: "வரைபடத்தில் காண", topRated: "சிறந்த மதிப்பீடு", recommended: "உங்களுக்கான பரிந்துரை", recentlyAdded: "சமீபத்தில் சேர்க்கப்பட்டவை", viewAll: "அனைத்தும் காண", statsStudents: "செயலில் மாணவர்கள்", statsListings: "சரிபார்க்கப்பட்ட அறைகள்", statsReviews: "மாணவர் மதிப்புரைகள்", statsOwners: "சரிபார்க்கப்பட்ட உரிமையாளர்கள்" },
      listing: { price: "விலை", perMonth: "/மாதம்", deposit: "வைப்பு", distance: "தூரம்", fromCampus: "வளாகத்திலிருந்து", facilities: "வசதிகள்", rules: "விதிகள்", reviews: "மதிப்புரைகள்", writeReview: "மதிப்புரை எழுது", contactOwner: "உரிமையாளரை தொடர்பு கொள்ள", verified: "சரிபார்க்கப்பட்டது", available: "கிடைக்கிறது", occupied: "நிரம்பியுள்ளது", pending: "நிலுவையில்", single: "தனி அறை", shared: "பகிர்ந்த அறை", "full house": "முழு வீடு", addToFav: "பிடித்தவைக்கு சேர்", removeFromFav: "பிடித்தவையிலிருந்து நீக்கு", viewDetails: "விவரங்கள் காண", ownerInfo: "உரிமையாளர் தகவல்", tenantPref: "குத்தகைதாரர் விருப்பம்", boysOnly: "ஆண்கள் மட்டும்", girlsOnly: "பெண்கள் மட்டும்", anyone: "யாவருக்கும்", noResults: "அறைகள் கிடைக்கவில்லை", tryDifferent: "வடிகட்டிகளை மாற்றி முயற்சிக்கவும்" },
      filter: { priceRange: "விலை வரம்பு", roomType: "அறை வகை", allTypes: "அனைத்து வகைகள்", maxDistance: "அதிகபட்ச தூரம்", searchPlaceholder: "அறைகளை தேடு...", applyFilters: "வடிகட்டிகளை பயன்படுத்து", clearAll: "அனைத்தையும் நீக்கு", sortBy: "வரிசைப்படுத்து", newest: "புதியவை", priceLow: "குறைந்த விலை", priceHigh: "அதிக விலை", rating: "சிறந்த மதிப்பீடு" },
      auth: { login: "உள்நுழைக", register: "கணக்கை உருவாக்கு", email: "மின்னஞ்சல் முகவரி", password: "கடவுச்சொல்", confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து", name: "முழு பெயர்", phone: "தொலைபேசி எண்", loginTitle: "மீண்டும் வரவேற்கிறோம்", loginSubtitle: "உங்கள் தங்கும் அறையைக் கண்டறிய உள்நுழையவும்", registerTitle: "UniBoard இல் இணையுங்கள்", registerSubtitle: "தொடங்க கணக்கை உருவாக்கவும்", asStudent: "மாணவராக", asOwner: "அறை உரிமையாளராக", orContinueWith: "அல்லது இதன் மூலம் தொடரவும்", googleSignIn: "Google உடன் தொடரவும்", noAccount: "கணக்கு இல்லையா?", hasAccount: "ஏற்கனவே கணக்கு உள்ளதா?", forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?" },
      owner: { dashboard: "உரிமையாளர் டாஷ்போர்டு", myRooms: "என் அறைகள்", addRoom: "புதிய அறை சேர்", editRoom: "அறையை திருத்து", totalViews: "மொத்த பார்வைகள்", totalFavorites: "மொத்த பிடித்தவை", activeListings: "செயலில் அறைகள்", roomTitle: "அறை தலைப்பு", roomDesc: "விளக்கம்", roomPrice: "மாத வாடகை (ரூ.)", roomDeposit: "பாதுகாப்பு வைப்பு (ரூ.)", roomAddress: "முகவரி", roomFacilities: "வசதிகள்", roomType: "அறை வகை", uploadPhotos: "புகைப்படங்கள் பதிவேற்றம்", dropPin: "வரைபடத்தில் குறிக்கவும்", tenantPref: "குத்தகைதாரர் விருப்பம்", gender: "பாலின விருப்பம்", saveListing: "சேமிக்கவும்", markAvailable: "கிடைக்கும் என குறி", markOccupied: "நிரம்பியது என குறி", deleteListing: "நீக்கு", analytics: "பகுப்பாய்வு", viewsThisWeek: "இந்த வார பார்வைகள்", favsThisWeek: "இந்த வார பிடித்தவை", basicInfo: "அடிப்படை தகவல்", contactInfo: "தொடர்பு தகவல்", locationMap: "இடம் மற்றும் வரைபடம்" },
      admin: { dashboard: "நிர்வாக டாஷ்போர்டு", overview: "கண்ணோட்டம்", users: "பயனர்கள்", verifications: "சரிபார்ப்புகள்", listings: "அறைகள்", totalUsers: "மொத்த பயனர்கள்", students: "மாணவர்கள்", owners: "உரிமையாளர்கள்", activeListings: "செயலில் அறைகள்", pendingListings: "நிலுவை அறைகள்", pendingVerifications: "நிலுவை சரிபார்ப்புகள்", approve: "ஏற்கவும்", reject: "நிராகரிக்கவும்", ban: "தடை செய்", unban: "தடை நீக்கு", viewDoc: "ஆவணம் காண", resolve: "தீர்க்கவும்", dismiss: "நிராகரிக்கவும்" },
      facilities: { kitchen: "சமையலறை", bathroom: "இணைக்கப்பட்ட குளியலறை", parking: "வாகன நிறுத்தம்", laundry: "சலவை", security: "பாதுகாப்பு", furnished: "அலங்கரிக்கப்பட்ட", water: "24/7 தண்ணீர்", electricity: "மின்சாரம்", tv: "TV" },
      footer: { about: "UniBoard பற்றி", aboutDesc: "கிழக்கு பல்கலைக்கழகம் திருகோணமலை மாணவர்களுக்கு பாதுகாப்பான தங்கும் அறைகளைக் கண்டறிய உதவும் தளம்.", quickLinks: "விரைவு இணைப்புகள்", support: "ஆதரவு", legal: "சட்ட", contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்", helpCenter: "உதவி மையம்", terms: "சேவை விதிமுறைகள்", privacy: "தனியுரிமை கொள்கை", rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை." }
    }
  }
};

i18n.use(initReactI18next).init({
  resources, lng: 'en', fallbackLng: 'en',
  interpolation: { escapeValue: false }
});

export default i18n;
*/